version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 99
  target-branch: develop
  labels:
  - type/dependencies
  - state/awaiting-reviews
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: gulp-replace
    versions:
    - 1.1.0
