language: node_js

node_js:
  - 10

# Stop as soon as an error is trigerred
matrix:
  fast_finish: true

# Caching node_modules folder for speed up build
cache: npm

before_install:
  - sh preinstall.sh
